logging:
  level:
    org:
    springframework: error



application:
  security:
    jwt:
      secret-key: bGbWqUxYztvCj8FzNO8GuJYY/YzkrU9wGx9+gaGwBo+Dmw0c70GFGZhtp2vw+1uq
      expiration: 86400000
      refresh-token:
        expiration: 604800000



server:
  port: 8082


aws:
  region: eu-north-1
  s3:
    buckets:
      user: loomo-user-data
      postVideos: loomo-post-videos
      postImage: loomo-post-image


spring:
  datasource:
#    url: jdbc:postgresql://localhost:5433/loomo
    url: jdbc:postgresql://16.170.234.255:5432/loomo
    username: postgres
    password: sardor
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  codec:
    max-in-memory-size: 100MB
  cassandra:
    contact-points: 16.170.234.255
    keyspace-name: loomo_keyspace
    port: 9042
    replication:
      class: SimpleStrategy
      replication-factor: 1
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
  elasticsearch:
    rest:
      cluster-nodes: 16.170.234.255:9200
      cluster-name: docker-cluster
